# Generated by Django 4.1.3 on 2023-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('like', models.BooleanField(null=True)),
                ('dis_like', models.BooleanField(null=True)),
            ],
        ),
    ]
