# Generated by Django 4.1.3 on 2023-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dis_like',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
    ]
